# Generated by Django 5.1.3 on 2024-11-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido_total_alter_produto_preco_carrinho_entregador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.RenameField(
            model_name='carrinho',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='entregador',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='status',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='app.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone_entrega',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.carrinho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.DeleteModel(
            name='PedidoProduto',
        ),
    ]
