# Generated by Django 5.1.3 on 2024-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_nome_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
    ]
